#!/bin/bash
python3 -m venv venv --prompt facecon
. venv/bin/activate
installed=`pip freeze`
current=`cat requirements.txt`
if [[ "$installed" != "$current" ]]; then
    pip install -r requirements.txt
fi
deactivate